name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
